default:
  paths:
    features: '%behat.paths.base%/../features'
    bootstrap:  '%behat.paths.features%/bootstrap'
  extensions:
    Behat\MinkExtension\Extension:
      base_url: http://localhost:4567/
      javascript_session: selenium2
      browser_name: firefox
      goutte: ~
      selenium2: ~
